resource "kubernetes_deployment" "example" {
  metadata {
    name = "terraform-example"
    labels = {
      test = "MyExampleApp"
    }
  }
 spec {
    replicas = 3

    selector {
      match_labels = {
        test = "mysql-kubernetes"
      }
    }

    template {
      metadata {
        labels = {
          test = "mysql-kubernetes"
        }
      }
      spec {
        container {
          image = "agboolab/basic-rest-api"
          name  = "app"

          resources {
            limits = {
              cpu    = "0.5"
              memory = "512Mi"
            }
            requests = {
              cpu    = "250m"
              memory = "50Mi"
            }
          }
          env: 
          - name: STAMPS
            valueFrom:
              configMapKeyRef:
                name: stamp-configmap 
                key: database_url
  